name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-main-infrastructure-to-dev:
    needs: deploy-openai-infrastructure-to-dev
    uses: ./.github/workflows/main-infrastructure.yaml
    with:
      environment: dev
    secrets: inherit

  deploy-main-infrastructure-to-prod:
    needs: deploy-openai-infrastructure-to-prod
    uses: ./.github/workflows/main-infrastructure.yaml
    with:
      environment: prod
    secrets: inherit
